"""Verify actual publication, all historic sources, controls and local MCP log."""
import json,sys
from pathlib import Path
from experiment_review import ROOT,read,sha,check_bindings
sys.path.insert(0,str(ROOT))
from mcp_readonly.catalog_io import load_catalog

def main():
    out=ROOT/'artifacts/v168_results_20261002';target=out/'validation.json';assert not target.exists();publication=read(out/'publication.json');check_bindings(publication['source_sha256']);actual=read(out/'actual_result_summary.json');check_bindings(actual['source_sha256']);before=load_catalog(ROOT,out/'previous/mcp_readonly/catalog.json',256*1024);current=load_catalog(ROOT,ROOT/'mcp_readonly/catalog.json',256*1024);old={r['id']:r for r in before['documents']};now={r['id']:r for r in current['documents']};assert len(old)==451 and len(now)==454 and all(now[k]==v for k,v in old.items())
    for row in now.values():assert sha(ROOT/row['path'])==row['sha256'] and (ROOT/row['path']).stat().st_size<=256*1024
    manifest=read(ROOT/'mcp_readonly/catalog.json');archive=ROOT/manifest['historical_catalog']['path'];assert archive.stat().st_size==262091<=256*1024 and sha(archive)==manifest['historical_catalog']['sha256'];assert (ROOT/'mcp_readonly/catalog.json').stat().st_size==publication['catalog_bytes']<=256*1024
    assert current['project']['authoritative_direction_id']=='v168-review' and current['project']['authoritative_delivery_id']=='v159-delivery';body=(out/'review.md').read_bytes();assert body==(ROOT/'docs/V168_COMPLETE_DECISION_FLOOR_DIAGNOSTIC_RESULTS_20261002.md').read_bytes();text=body.decode('utf-8');assert all(v in text for v in before['project']['known_limits']);prior=(ROOT/'artifacts/v167_direction_20261002/plan.md').read_text(encoding='utf-8').split('## 既有证据限制完整保留\n\n',1)[1];assert prior in text
    assert actual['actual_new_heads']==98 and actual['actual_new_complete_margin_derivatives']==50 and actual['actual_QP_solves']==actual['actual_finite_proposals']==1 and actual['cumulative_heads']==19178 and actual['cumulative_all_complete_derivatives']==768 and actual['new_fits']==actual['permanent_updates']==0 and actual['all_restored_full_tensors_exact'] and actual['all_restored_original_argmax_exact'];assert actual['supports_separate_short_training_registration'] and actual['no_fit_authority_under_current_contract'] and not actual['classification_mastery'] and not actual['quality_acceptance'];assert actual['latest_actual_training']=='V164' and actual['latest_complete_quality_delivery']=='V159'
    root=ROOT/'artifacts/v168_independent_actual_decision_floor_review_20261002/review.json';audit=read(root);assert audit['all_three_actual_finite_candidates_safe'] and not audit['training_issue_mastered'] and not audit['quality_acceptance'] and audit['official_calls_by_this_review']==0;replay=ROOT/'artifacts/v168_observed_runtime_boundaries_20261002/replay.json';assert len(read(replay)['cases'])==5 and read(replay)['no_new_execution_authority'];check_bindings(read(replay)['source_sha256'])
    log=ROOT/'artifacts/v168_complete_results_MCP_tests_original_console_20261002.txt';console=log.read_text(encoding='utf-8');assert 'Ran 23 tests' in console and console.rstrip().endswith('OK');assert sha(ROOT/'training/experiment_review.py')=='a0faa3312cbb39d3c6bcb62d7a2b290fe18eae14579278b0ff26479fdf2b768e'
    paths=[Path(__file__).resolve(),out/'publication.json',out/'actual_result_summary.json',out/'review.md',root,replay,log,archive,ROOT/'README.md',ROOT/'HANDOFF.md',ROOT/'mcp_readonly/catalog.json',ROOT/'mcp_readonly/catalog_io.py',ROOT/'mcp_readonly/server.py',ROOT/'mcp_readonly/tests/test_readonly_mcp.py',ROOT/'mcp_readonly/tests/test_catalog_archive.py'];target.write_bytes((json.dumps(dict(status='V168_complete_actual_publication_451_historic_records_and_23_local_MCP_tests_verified',historical_document_metadata_preserved=451,effective_documents=454,new_documents=3,current_direction='v168-review',latest_actual_training='V164',latest_complete_quality_delivery='V159',MCP_tests_passed=23,MCP_scope='local_tool_and_HTTP_TestClient_only_no_cloud_live_acceptance',old_full_population_delivery_unchanged=True,all_old_limits_preserved=True,all_archive_ID_path_hash_metadata_and_actual_contents_preserved=True,single_finite_success_not_training_mastery=True,official_calls=0,new_fits=0,permanent_updates=0,root_goal_complete=False,source_sha256={p.relative_to(ROOT).as_posix():sha(p) for p in paths}),ensure_ascii=False,indent=2)+'\n').encode('utf-8'));print(json.dumps(dict(status='V168_full_publication_verified',historic_records=451,MCP_tests=23,official_calls=0)))

if __name__=='__main__':main()
