"""Executable observed boundaries of the actual successful finite diagnostic."""
import json
from pathlib import Path
from experiment_review import ROOT,read,sha,check_bindings

OUT=ROOT/'artifacts/v168_observed_runtime_boundaries_20261002'
REGISTRY=ROOT/'training/review_policy/v168_observed_runtime_boundaries.json'

def main():
    assert not OUT.exists() and not REGISTRY.exists();quality=ROOT/'artifacts/v168_saved_decision_floor_quality_review_20261002/review.json';geometry=ROOT/'artifacts/v168_saved_actual_floor_geometry_review_20261002/review.json';audit=ROOT/'artifacts/v168_independent_actual_decision_floor_review_20261002/review.json';prior=ROOT/'artifacts/v168_root_saved_prior_burden_review_20261002/review.json';diagpath=ROOT/'artifacts/v168_decision_floor_diagnostic_20261002/role1/diagnostic.json';q,g,a,p,d=map(read,[quality,geometry,audit,prior,diagpath])
    for path in [quality,geometry,prior,audit.parent/'pre_review_bindings.json']:check_bindings(read(path)['source_sha256'])
    assert a['all_three_actual_finite_candidates_safe'] and a['supports_new_short_training_registration'] and not a['training_issue_mastered'] and not a['quality_acceptance']
    assert q['actual_new_heads']==a['new_heads']==98 and q['actual_new_complete_margin_derivatives']==a['new_complete_margin_derivatives']==50 and q['actual_QP_solves']==a['actual_QP_solves']==1
    assert d['all_parameters_restored'] and d['new_fits']==d['permanent_updates']==0 and d['actual_finite_accepted']
    tie=g['previous_actual_tie_function_geometry'];assert len(tie)==1 and tie[0]['actual_argmax']==2 and tie[0]['actual_log_margin']==3.552713678800501e-15 and tie[0]['actual_probability_margin']==1.7763568394002505e-15 and not tie[0]['actual_exact_q_tie']
    paired=q['all_finite_candidates'][0]['paired_vs_V164'];assert paired['M']['repairs_vs_previous_accepted']==4 and paired['M']['new_errors_vs_previous_accepted']==0 and paired['S']['repairs_vs_previous_accepted']==paired['S']['new_errors_vs_previous_accepted']==0
    burden=p['roles'][1]['classes']['S'];assert burden['errors']==1156 and burden['truth_prior_at_or_below_fixed_floor']==813 and burden['errors_impossible_if_only_hidden_changes_and_current_readout_frozen']==1082 and burden['all_parameters_remain_trainable'] and burden['frozen_readout_bound_not_global_model_infeasibility']
    cases=[dict(id='V168-ACTUAL-SAFE-TINY-MARGIN-NOT-STABILITY',evidence=geometry.relative_to(ROOT).as_posix(),actual_fact='The two previous S ties are now correct with log margin3.552713678800501e-15 and q gap1.7763568394002505e-15; one actual candidate passed',required_action='Keep exact argmax and all original guards. Do not claim independent transfer, multiple-state repeat stability or mastery from this single tiny decision margin'),dict(id='V168-S-RESTORATION-NOT-NEW-S-ERROR-REPAIR',evidence=quality.relative_to(ROOT).as_posix(),actual_fact='Versus V167 the two S regressions disappear; versus V164 there are4M repairs and0S old-error repairs, with0new M/S errors and1948 remaining pure role1 errors',required_action='Report both baselines and remaining per-class errors. Do not count restoring original correctness as repairing V164 S errors or hide serious remaining errors with total loss'),dict(id='V168-FINITE-DIAGNOSTIC-NOT-NEW-TRAINED-MODEL',evidence=diagpath.relative_to(ROOT).as_posix(),actual_fact='98heads/50derivatives/1QP/1candidate,0fits/0permanent updates and complete V164 restore; safe roles0/2 use immutable old references',required_action='Keep cumulative19178heads/768derivatives, latest real trainingV164 and full deliveryV159. No second correction or fit under this contract; unchanged safe controls have no new gains'),dict(id='V168-FROZEN-READOUT-BURDEN-NOT-GLOBAL-INFEASIBILITY',evidence=prior.relative_to(ROOT).as_posix(),actual_fact='At V164 role1,813of1156 S errors have truth prior at or below1e-12;1082 cannot be repaired while current readout is frozen, but all model parameters remain trainable',required_action='Track deep prior margins, learned residuals, readout scale and actual repairs. Do not claim model-wide impossibility, missing information or solve classification using temperature calibration'),dict(id='V168-ELIGIBLE-FOR-REGISTRATION-NOT-AUTOMATIC-TRAINING',evidence=audit.relative_to(ROOT).as_posix(),actual_fact='Independent original-gold audit passes the single finite diagnostic and frozen safe controls, but training_issue_mastered and quality_acceptance remain false',required_action='Register a new single-issue bounded training contract with complete protection, real accepted trajectory and deep-error progress. Preserve V164 capacity stops and failed budgets; do not rerun the old entry or substitute this result for pure-error-zero and five distinct mastered states')]
    registry=dict(schema_version=1,actual_diagnostic='V168',inherit_applicable_constraints='training/review_policy/v167_observed_runtime_boundaries.json',cases=cases,no_new_execution_authority=True,executable_constraint_replay='training/v168_record_observed_boundaries.py',scope='Actual supervised development finite diagnostic and state-dependent saved readout bounds only; no full task or independent-source acceptance')
    OUT.mkdir();REGISTRY.write_bytes((json.dumps(registry,ensure_ascii=False,indent=2)+'\n').encode('utf-8'));sources=[Path(__file__).resolve(),REGISTRY,quality,geometry,audit,audit.parent/'pre_review_bindings.json',prior,diagpath,ROOT/registry['inherit_applicable_constraints']];bindings={path.relative_to(ROOT).as_posix():sha(path) for path in sources};check_bindings(bindings);(OUT/'replay.json').write_bytes((json.dumps(dict(status='V168_five_actual_success_and_remaining_failure_boundaries_replayed',cases={r['id']:dict(passed=True,evidence=r['evidence']) for r in cases},official_calls=0,new_fits=0,permanent_updates=0,classification_mastery=False,quality_acceptance=False,no_new_execution_authority=True,source_sha256=bindings),ensure_ascii=False,indent=2)+'\n').encode('utf-8'));print(json.dumps(dict(status='V168_observed_boundaries_replayed',cases=5,official_calls=0)))

if __name__=='__main__':main()
