"""New entry version: lossless support encoding, direction recipes and original row factors."""
from experiment_review import ROOT,sha
from v169_prepare_training_entry_v2 import change

def main():
    old=ROOT/'training/v169_prior_pair_training_entry_v3.py';target=ROOT/'training/v169_prior_pair_training_entry_v4.py'
    if target.exists():raise FileExistsError(target)
    text=old.read_text(encoding='utf-8')
    text=change(text,'from v169_exact_gradient_storage import save_vector,load_vector','from v169_structural_vector_storage import save_vector,load_vector,digest,reconstruction\nfrom v169_factorized_row_evidence import save_scope as factorized_scope')
    text=change(text,"self.folder.mkdir();self.ctx=load_context(role)","self.folder.mkdir();self.ctx=load_context(role)\n        self.global_columns=np.unique(self.ctx['x'].indices)\n        self.target_columns={cls:np.unique(self.ctx['x'][np.flatnonzero(self.ctx['target_counts'][:,cls])].indices) for cls in [1,2]}")
    text=change(text,"save_vector(folder/f'class{cls}_repeat{repetition}.npz',g)","save_vector(folder/f'class{cls}_repeat{repetition}.npz',g,self.target_columns[cls])")
    text=change(text,'    def _trial(self,u,slopes,label):','    def _trial(self,u,slopes,label,recipe=None):')
    text=change(text,"self._persist_observation(folder,ob);save_vector(folder/'displacement.npz',np.asarray(u,np.float64))", "self._persist_observation(folder,ob)\n            if recipe is None:\n                source=folder/'displacement.npz';save_vector(source,np.asarray(u,np.float64),self.global_columns)\n                recipe=dict(kind='stored',source=source.relative_to(ROOT).as_posix(),source_sha256=sha(source),width=width(self.arm),dense_sha256=digest(u))\n            if reconstruction(recipe,ROOT).tobytes()!=np.asarray(u,np.float64).tobytes():raise RuntimeError('Lossless complete displacement recipe mismatch')\n            save(folder/'displacement_recipe.json',recipe)")
    text=change(text,"blocks.to_parquet(folder/'all_actual_blocking_original_rows.parquet',index=False)","np.savez_compressed(folder/'all_blocking_original_row_identity.npz',row_position=blocks.row_position.to_numpy(),local=blocks.local.to_numpy(),truth=blocks.truth.to_numpy(),rival=blocks.rival.to_numpy(),scope=blocks.scope.to_numpy(dtype=str))")
    text=change(text,'result=dict(ob,accepted=accepted,blockers=blocks,u=u,folder=folder,guard=guard,finite=finite)','result=dict(ob,accepted=accepted,blockers=blocks,u=u,folder=folder,guard=guard,finite=finite,recipe=recipe)')
    text=change(text,"        trial=None\n        for backtrack in range(8):", "        source=folder/'complete_common_direction.npz';save_vector(source,result['direction'],self.global_columns)\n        trial=None\n        for backtrack in range(8):")
    text=change(text,"            trial=self._trial(u,[float(g@u) for g in gs],f'point{state}_line{backtrack}')", "            recipe=dict(kind='scaled',source=source.relative_to(ROOT).as_posix(),source_sha256=sha(source),step_hex=float(step).hex(),width=width(self.arm),dense_sha256=digest(u))\n            trial=self._trial(u,[float(g@u) for g in gs],f'point{state}_line{backtrack}',recipe)")
    text=change(text,"save_vector(target/f'repeat{repetition}.npz',value['gradient']);", "save_vector(target/f'repeat{repetition}.npz',value['gradient'],self.ctx['x'][[local]].indices);")
    text=change(text,"        save_vector(folder/'correction.npz',result['correction'])\n        return self._trial(result['displacement'],[r['linear_change'] for r in result['class_reviews']],f'point{state}_correction{correction}_trial')", "        source=folder/'correction.npz';save_vector(source,result['correction'],self.global_columns)\n        recipe=dict(kind='added',parent=trial['recipe'],correction=source.relative_to(ROOT).as_posix(),correction_sha256=sha(source),width=width(self.arm),dense_sha256=digest(result['displacement']))\n        return self._trial(result['displacement'],[r['linear_change'] for r in result['class_reviews']],f'point{state}_correction{correction}_trial',recipe)")
    text=change(text,"            for scope in ['OOF','deployment']:store_scope(target,self.ctx,scope,trial[f'{scope}_q'],trial[f'{scope}_logq'])\n            self.ctx['OOF_rows'].loc[old|repair,['row_position','local','truth','root','pure_current_input']].to_parquet(target/'complete_cumulative_protection.parquet',index=False)", "            for scope in ['OOF','deployment']:\n                rr=self.ctx[scope+'_rows'];factorized_scope(target/scope,ROOT,PRIOR/f'role{self.role}/endpoint/{scope}_original_rows.parquet',trial[f'{scope}_q'],trial[f'{scope}_logq'],rr.protected_correct.to_numpy(bool))\n            np.save(target/'complete_cumulative_original_row_protection.npy',old|repair)")
    target.write_bytes(text.encode('utf-8'));print(dict(status='V169_factorized_entry_v4_prepared_full_dimensions_and_raw_bits_preserved',old_sha256=sha(old),new_sha256=sha(target),official_calls=0))

if __name__=='__main__':main()
