"""Final stable source closure, live RAM accounting and commit-aware seal."""
from experiment_review import ROOT

def main():
    source=ROOT/'training/v169_factorized_resource_budget_v6.py';target=ROOT/'training/v169_factorized_resource_budget_v7.py';assert not target.exists();s=source.read_text(encoding='utf-8').replace('v169_factorized_resource_budget_v6_20261002','v169_factorized_resource_budget_v7_20261002')
    old="    ram_bound=8*66*1060833*8+GiB;assert ram_bound<resources['minimum_free_RAM_bytes']"
    new="    live_RAM=read(source[-4]);ram_bound=8*66*1060833*8+live_RAM['measured_base_live_resident_increment_after_import']+live_RAM['extra_physical_slack_bytes'];assert ram_bound==5936980096 and ram_bound<resources['minimum_free_RAM_bytes']"
    assert old in s;s=s.replace(old,new).replace('RAM_array_accounting_upper_bytes=ram_bound','RAM_complete_live_phase_accounting_upper_bytes=ram_bound,QP_eight_matrix_accounting_upper_bytes=8*66*1060833*8')
    compile(s,str(target),'exec');target.write_text(s,encoding='utf-8')
    # This candidate generator has not executed or been bound yet.
    candidate_source=ROOT/'training/v169_prepare_execution_contract_candidate_v3.py';s=candidate_source.read_text(encoding='utf-8');assert 'v169_factorized_resource_budget_v6_20261002' in s;s=s.replace('v169_factorized_resource_budget_v6_20261002','v169_factorized_resource_budget_v7_20261002');candidate_source.write_text(s,encoding='utf-8')
    source=ROOT/'training/v169_seal_prior_pair_training_v2.py';target=ROOT/'training/v169_seal_prior_pair_training_v3.py';assert not target.exists();s=source.read_text(encoding='utf-8').replace('v169_full_preseal_bundle_v3_20261002','v169_full_preseal_bundle_v4_20261002').replace('v169_prior_pair_execution_contract_candidate_v2.json','v169_prior_pair_execution_contract_candidate_v3.json').replace('v169_prior_pair_training_entry_v12','v169_prior_pair_training_entry_v13')
    old="    state=MemoryStatus();state.length=ctypes.sizeof(state);assert ctypes.windll.kernel32.GlobalMemoryStatusEx(ctypes.byref(state))\n    free=shutil.disk_usage(ROOT).free;gpu_free,gpu_total=torch.cuda.mem_get_info()"
    new="    free=shutil.disk_usage(ROOT).free;gpu_free,gpu_total=torch.cuda.mem_get_info()\n    state=MemoryStatus();state.length=ctypes.sizeof(state);assert ctypes.windll.kernel32.GlobalMemoryStatusEx(ctypes.byref(state))\n    from v169_pair_execution_review_v4 import check_memory\n    check_memory(plan['resources'],state.avail_phys,state.avail_page)"
    assert old in s;s=s.replace(old,new).replace('free_RAM_bytes=state.avail_phys,free_GPU_bytes=','free_RAM_bytes=state.avail_phys,free_commit_bytes=state.avail_page,free_GPU_bytes=');target.write_text(s,encoding='utf-8')
    source=ROOT/'training/v169_prepare_full_preseal_bundle_v3.py';target=ROOT/'training/v169_prepare_full_preseal_bundle_v4.py';assert not target.exists();s=source.read_text(encoding='utf-8').replace('v169_prior_pair_training_entry_v12','v169_prior_pair_training_entry_v13').replace('v169_full_preseal_bundle_v3_20261002','v169_full_preseal_bundle_v4_20261002').replace('v169_prior_pair_execution_contract_candidate_v2.json','v169_prior_pair_execution_contract_candidate_v3.json').replace('v169_actual_backend_synthetic_qualification_v3','v169_actual_backend_synthetic_qualification_v4').replace("'v169_execution_contract_candidate_v2'","'v169_execution_contract_candidate_v3','v169_memory_exact_solver_qualification','v169_cuda_host_buffer_qualification_v2','v169_physical_and_commit_policy_qualification'").replace("'v169_factorized_resource_budget_v5'","'v169_factorized_resource_budget_v7'").replace('V169_final_v12','V169_final_v13').replace('v169_prepare_full_preseal_bundle_v3_original_console_20261002.txt','v169_prepare_full_preseal_bundle_v4_original_console_20261002.txt')
    old="    for path in (ROOT/'training').glob('v169*.py'):files.add(path)"
    new="    for name in ['v169_saved_storage_filecount_review','v169_incremental_RAM_live_buffer_review']:\n        directory=ROOT/f'artifacts/{name}_20261002';files.update(p for p in directory.rglob('*') if p.is_file())\n    for path in (ROOT/'training').glob('v169*.py'):files.add(path)"
    assert old in s;s=s.replace(old,new);compile(s,str(target),'exec');target.write_text(s,encoding='utf-8');print('Prepared resource v7, sealer v3 and stable full bundle v4')

if __name__=='__main__':main()
